---
###############################################################################
# Fonts Install
###############################################################################
# Install custom fonts.
#
#
# Reference:
# * https://wiki.debian.org/Fonts#Adding_fonts

- name: 'Install packages'
  ansible.builtin.include_role:
    name: 'r_pufky.srv.apt'
  vars:
    apt_packages:
      - '{{ fonts_role_packages }}'
      - '{{ fonts_packages }}'
    apt_package_update_cache: true

- name: 'Copy custom fonts'
  notify:
    - 'Handlers | refresh font cache'
  ansible.posix.synchronize:
    src: '{{ fonts_source }}'
    dest: '{{ fonts_path }}'
    delete: true
    recursive: true
    archive: false
    checksum: true

- name: 'Set permissions'
  ansible.builtin.shell: |
    chown -R root:staff '{{ fonts_path }}' &&
    find '{{ fonts_path }}' -type d -exec chmod 0755 {} \; &&
    find '{{ fonts_path }}' -type f -exec chmod 0644 {} \;
  changed_when: false
