---
# yamllint disable rule:line-length
###############################################################################
# Default
###############################################################################
# Use a Google public domain font for testing font installation. Store in a
# static temporary location to cache downloaded fonts between tests instead of
# using tempfile.
#
# Reference:
# * https://github.com/google/fonts

- name: 'Default | prepare'
  hosts: 127.0.0.1
  connection: local
  gather_facts: false
  tasks:
    - name: 'Default | prepare | cache'
      ansible.builtin.include_role:
        name: 'r_pufky.lib.tests'
        tasks_from: 'create_cache.yml'
      vars:
        test_name: 'Default | prepare | cache'

    - name: 'Default | prepare | cache | fonts-test-font.ttf'
      ansible.builtin.include_role:
        name: 'r_pufky.lib.tests'
        tasks_from: 'cache_url.yml'
      vars:
        test_name: 'Default | prepare | cache | fonts-test-font.ttf'
        test_dest: 'fonts-test-font.ttf'
        test_url: 'https://github.com/google/fonts/blob/main/ufl/ubuntu/Ubuntu-Regular.ttf'

- name: 'Default | prepare | inject fonts'
  hosts: 'all'
  gather_facts: false
  tasks:
    - name: 'Default | prepare | generate cache location'
      ansible.builtin.set_fact:
        _test_cache:
          '{{ lookup("env", "MOLECULE_PROJECT_DIRECTORY") }}/molecule/cache'

    - name: 'Default | prepare | inject fonts directory'
      ansible.builtin.file:
        path: '/usr/local/share/fonts/ansible/fonts'
        mode: '0755'
        state: 'directory'

    - name: 'Default | prepare | inject font file to be deleted'
      ansible.builtin.copy:
        src: '{{ _test_cache }}/fonts-test-font.ttf'
        dest: '/usr/local/share/fonts/ansible/fonts/should-be-deleted.ttf'
        mode: '0644'
        directory_mode: '0755'
      become: true
