---
- name: 'Default | verify | all test systems have test font installed'
  hosts: 'all'
  gather_facts: false
  tasks:
    - name: 'Default | verify | fonts-test-font.ttf'
      ansible.builtin.include_role:
        name: 'r_pufky.lib.tests'
        tasks_from: 'file.yml'
      vars:
        test_name: 'Default | verify | fonts-test-font.ttf'
        test_file: '/usr/local/share/fonts/ansible/fonts-test-font.ttf'
        test_owner: 'root'
        test_group: 'staff'
        test_mode: '0644'
        test_state: 'file'

    - name: 'Default | verify | should-be-deleted.ttf'
      ansible.builtin.include_role:
        name: 'r_pufky.lib.tests'
        tasks_from: 'file.yml'
      vars:
        test_name: 'Default | verify | should-be-deleted.ttf'
        test_file: '/usr/local/share/fonts/ansible/should-be-deleted.ttf'
        test_owner: '{{ omit }}'
        test_group: '{{ omit }}'
        test_mode: '{{ omit }}'
        test_state: 'absent'
